/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main_testd.c                                       :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: abesombe <abesombe@42.fr>                  +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2020/12/12 09:55:52 by abesombe          #+#    #+#             */
/*   Updated: 2020/12/31 00:30:13 by abesombe         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include <stdio.h>
#include "../ft_printf.h"

int main(void)
{
	int d = 21;

	printf("\n\n--------TEST D = 21 POSITIVE NUMBER ---------"); 
	printf("\n\n--------TEST 1: %%d---------");
	printf("\n[%d]\n", d);
	ft_printf("[%d]", d);
	printf("\n\n--------TEST 2: %%5d---------");
	printf("\n[%5d]\n", d);
	ft_printf("[%5d]", d);
	printf("\n\n--------TEST 2 bis: d = 1234567890 et %%5d---------");
	printf("\n[%5d]\n", 1234567890);
	ft_printf("[%5d]", 1234567890);
	printf("\n\n--------TEST 2 ter: d = 1234567890 et %%5.6d---------");
	printf("\n[%5.6d]\n", 1234567890);
	ft_printf("[%5.6d]", 1234567890);
	printf("\n\n--------TEST 3: %%-5d---------");
	printf("\n[%-5d]\n", d);
	ft_printf("[%-5d]", d);
	printf("\n\n--------TEST 4: %%05d---------");
	printf("\n[%05d]\n", d);
	ft_printf("[%05d]", d);
	printf("\n\n--------TEST 4 bis: %%-05d---------");
	printf("\n[%-05d]\n", d);
	ft_printf("[%-05d]", d);
	printf("\n\n--------TEST 5: %%+5d---------");
	printf("\n[%+5d]\n", d);
	ft_printf("[%+5d]", d);
	printf("\n\n--------TEST 5 bis: %%+2d---------");
	printf("\n[%+2d]\n", d);
	ft_printf("[%+2d]", d);
	printf("\n\n--------TEST 6: %%+05d---------");
	printf("\n[%+05d]\n", d);
	ft_printf("[%+05d]", d);
	printf("\n\n--------TEST 7: %%+-5d---------");
	printf("\n[%+-5d]\n", d);
	ft_printf("[%+-5d]", d);
	printf("\n\n--------TEST 8: %%+d---------");
	printf("\n[%+d]\n", d);
	ft_printf("[%+d]", d);
	printf("\n\n--------TEST 9: %%+*d---------");
	printf("\n[%+*d]\n", 5, d);
	ft_printf("[%+*d]", 5, d);
	printf("\n\n--------TEST 10: %%+-0*d---------");
	printf("\n[%+-0*d]\n", 10, d);
	ft_printf("[%+-0*d]", 10, d);
	printf("\n\n--------TEST 11: %%.6d---------");
	printf("\n[%.6d]\n", d);
	ft_printf("[%.6d]", d);
	printf("\n\n--------TEST 12: %%10.6d---------");
	printf("\n[%10.6d]\n", d);
	ft_printf("[%10.6d]", d);
	printf("\n\n--------TEST 13: %%-10.6d---------");
	printf("\n[%-10.6d]\n", d);
	ft_printf("[%-10.6d]", d);
	printf("\n\n--------TEST 14: %%010.6d---------");
	printf("\n[%010.6d]\n", d);
	ft_printf("[%010.6d]", d);
	printf("\n\n--------TEST 14 bis: %%010d---------");
	printf("\n[%010d]\n", d);
	ft_printf("[%010d]", d);
	printf("\n\n--------TEST 15: %%+10.6d---------");
	printf("\n[%+10.6d]\n", d);
	ft_printf("[%+10.6d]", d);
	printf("\n\n--------TEST 16: %%+010.6d---------");
	printf("\n[%+010.6d]\n", d);
	ft_printf("[%+010.6d]", d);
	printf("\n\n--------TEST 17: %%+-10.6d---------");
	printf("\n[%+-10.6d]\n", d);
	ft_printf("[%+-10.6d]", d);
	printf("\n\n--------TEST 17 bis: %% +-10.6d---------");
	printf("\n[% +-10.6d]\n", d);
	ft_printf("[% +-10.6d]", d);
	printf("\n\n--------TEST 17 bis bis: %% -10.6d---------");
	printf("\n[% -10.6d]\n", d);
	ft_printf("[% -10.6d]", d);
	printf("\n\n--------TEST 18: %%+.6d---------");
	printf("\n[%+.6d]\n", d);
	ft_printf("[%+.6d]", d);
	printf("\n\n--------TEST 19: %%+*.6d---------");
	printf("\n[%+*.6d]\n", 10, d);
	ft_printf("[%+*.6d]", 10, d);
	printf("\n\n--------TEST 20: %%+-0*.6d---------");
	printf("\n[%+-0*.6d]\n", 10, d);
	ft_printf("[%+-0*.6d]", 10, d);
	printf("\n\n--------TEST 21: %%-06d---------");
	printf("\n[%-06d]\n", d);
	ft_printf("[%-06d]", d);
	printf("\n\n--------TEST 22: %% -6d---------");
	printf("\n[% -6d]\n", d);
	ft_printf("[% -6d]", d);
	printf("\n\n--------TEST 23: %% -d---------");
	printf("\n[% -d]\n", d);
	ft_printf("[% -d]", d);
	printf("\n\n--------TEST 24: %% d---------");
	printf("\n[% d]\n", d);
	ft_printf("[% d]", d);
	printf("\n\n--------TEST 25: %% -.3d---------");
	printf("\n[% -.3d]\n", d);
	ft_printf("[% -.3d]", d);
	printf("\n\n--------TEST 26: %% -.4d---------");
	printf("\n[% -.4d]\n", d);
	ft_printf("[% -.4d]", d);
	printf("\n\n--------TEST 27: %% -.5d---------");
	printf("\n[% -.5d]\n", d);
	ft_printf("[% -.5d]", d);
	printf("\n\n--------TEST 28: %% -10.6d---------");
	printf("\n[% -10.6d]\n", d);
	ft_printf("[% -10.6d]", d);
	printf("\n\n--------TEST 29: %% +-d---------");
	printf("\n[% +-d]\n", d);
	ft_printf("[% +-d]", d);
	printf("\n\n--------TEST 30: %% +-6d---------");
	printf("\n[% +-6d]\n", d);
	ft_printf("[% +-6d]", d);
	printf("\n\n--------TEST 31: d = 0 - %% -6d---------");
	printf("\n[% -6d]\n", 0);
	ft_printf("[% -6d]", 0);
	printf("\n\n--------TEST 32: %% -6d---------");
	printf("\n[% -6d]\n", d);
	ft_printf("[% -6d]", d);
	
	d = -21;
	printf("\n\n--------TEST D = -21 NEGATIVE NUMBER ---------"); 
	printf("\n\n--------TEST 1: %%d---------");
	printf("\n[%d]\n", d);
	ft_printf("[%d]", d);
	printf("\n\n--------TEST 2: %%5d---------");
	printf("\n[%5d]\n", d);
	ft_printf("[%5d]", d);
	printf("\n\n--------TEST 3: %%-5d---------");
	printf("\n[%-5d]\n", d);
	ft_printf("[%-5d]", d);
	printf("\n\n--------TEST 4: %%05d---------");
	printf("\n[%05d]\n", d);
	ft_printf("[%05d]", d);
	printf("\n\n--------TEST 5: %%+5d---------");
	printf("\n[%+5d]\n", d);
	ft_printf("[%+5d]", d);
	printf("\n\n--------TEST 6: %%+05d---------");
	printf("\n[%+05d]\n", d);
	ft_printf("[%+05d]", d);
	printf("\n\n--------TEST 7: %%+5d---------");
	printf("\n[%+5d]\n", d);
	ft_printf("[%+5d]", d);
	printf("\n\n--------TEST 8: %%+d---------");
	printf("\n[%+d]\n", d);
	ft_printf("[%+d]", d);
	printf("\n\n--------TEST 9: %%-d---------");
	printf("\n[%-d]\n", d);
	ft_printf("[%-d]", d);
	printf("\n\n--------TEST 10: %%+-05d---------");
	printf("\n[%+-05d]\n", d);
	ft_printf("[%+-05d]", d);
	printf("\n\n--------TEST 11: %%05.d---------");
	printf("\n[%05.d]\n", d);
	ft_printf("[%05.d]", d);
	printf("\n\n--------TEST 12: %%.1d---------");
	printf("\n[%.1d]\n", d);
	ft_printf("[%.1d]", d);
	printf("\n\n--------TEST 13: %%0.1d---------");
	printf("\n[%0.1d]\n", d);
	ft_printf("[%0.1d]", d);
	printf("\n\n--------TEST 14: %%08.1d---------");
	printf("\n[%08.1d]\n", d);
	ft_printf("[%08.1d]", d);
	printf("\n\n--------TEST 15: %%+-0*d---------");
	printf("\n[%+-0*d]\n", 10, d);
	ft_printf("[%+-0*d]", 10, d);
	printf("\n\n--------TEST 16: %%.6d---------");
	printf("\n[%.6d]\n", d);
	ft_printf("[%.6d]", d);
	printf("\n\n--------TEST 17: %%10.6d---------");
	printf("\n[%10.6d]\n", d);
	ft_printf("[%10.6d]", d);
	printf("\n\n--------TEST 18: %%-10.6d---------");
	printf("\n[%-10.6d]\n", d);
	ft_printf("[%-10.6d]", d);
	printf("\n\n--------TEST 19: %%010.6d---------");
	printf("\n[%010.6d]\n", d);
	ft_printf("[%010.6d]", d);
	printf("\n\n--------TEST 20: %%+10.6d---------");
	printf("\n[%+10.6d]\n", d);
	ft_printf("[%+10.6d]", d);
	printf("\n\n--------TEST 21: %%+010.6d---------");
	printf("\n[%+010.6d]\n", d);
	ft_printf("[%+010.6d]", d);
	printf("\n\n--------TEST 22: %%+-10.6d---------");
	printf("\n[%+-10.6d]\n", d);
	ft_printf("[%+-10.6d]", d);
	printf("\n\n--------TEST 23: %%+.6d---------");
	printf("\n[%+.6d]\n", d);
	ft_printf("[%+.6d]", d);
	printf("\n\n--------TEST 24: %%+*.6d---------");
	printf("\n[%+*.6d]\n", 10, d);
	ft_printf("[%+*.6d]", 10, d);
	printf("\n\n--------TEST 25: %%+-0*.6d---------");
	printf("\n[%+-0*.6d]\n", 10, d);
	ft_printf("[%+-0*.6d]", 10, d);
	printf("\n\n--------TEST 26: %% .6d---------");
	printf("\n[% .6d]\n", d);
	ft_printf("[% .6d]", d);
	printf("\n\n--------TEST 27: %% 10.6d---------");
	printf("\n[% 10.6d]\n", d);
	ft_printf("[% 10.6d]", d);
	printf("\n\n--------TEST 28: %% -10.6d---------");
	printf("\n[% -10.6d]\n", d);
	ft_printf("[% -10.6d]", d);
	printf("\n\n--------TEST 29: %% 010.6d---------");
	printf("\n[% 010.6d]\n", d);
	ft_printf("[% 010.6d]", d);
	printf("\n\n--------TEST 30: %% +10.6d---------");
	printf("\n[% +10.6d]\n", d);
	ft_printf("[% +10.6d]", d);
	printf("\n\n--------TEST 31: %% +010.6d---------");
	printf("\n[% +010.6d]\n", d);
	ft_printf("[% +010.6d]", d);
	printf("\n\n--------TEST 32: %% +-10.6d---------");
	printf("\n[% +-10.6d]\n", d);
	ft_printf("[% +-10.6d]", d);
	printf("\n\n--------TEST 33: %% +.6d---------");
	printf("\n[% +.6d]\n", d);
	ft_printf("[% +.6d]", d);
	printf("\n\n--------TEST 34: %% +*.6d---------");
	printf("\n[% +*.6d]\n", 10, d);
	ft_printf("[% +*.6d]", 10, d);
	printf("\n\n--------TEST 35: %% +-0*.6d---------");
	printf("\n[% +-0*.6d]\n", 10, d);
	ft_printf("[% +-0*.6d]", 10, d);
}
